[package]
name = "code-file-concat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
glob = "0.3"
mj_io = "0.1.2"
rand = "0.9.0"
rayon = "1.10.0"
serde_json = "1.0.138"
